package genericresponse

const (
	INVALID_PAYLOAD = "INVALID PAYLOAD"
	INVALID_PARAM   = "INVALID_PARAM"
	NOT_FOUND       = "RESOURCE NOT FOUND"
	INVALID_TOKEN   = "INVALID TOKEN"
	FORBIDDEN       = "FORBIDDEN"
)
